### ISSUE TITLE
Issue running with unprivilege containers

### ISSUE THREAD

**Issue by rramos** [lxc/python2-lxc#10]
Hi,

  I'm trying to use ansible to create lxc unprivileged containers. 
  It uses python2-lxc but i can't seem to find a way to pass the `-t download` 
  option for the create execution.

 My example execution runs:

```
/usr/bin/lxc-create --name test001 --config ~/.config/lxc/default.conf --template ubuntu --bdev dir --logfile /home/rramos/lxc-test001.log --logpriority INFO -- -d ubuntu -r xenial -a amd64
```

but it should run:

```
/usr/bin/lxc-create -t download --name test001 --config ~/.config/lxc/default.conf  --logfile /home/rramos/lxc-test001.log --logpriority INFO -- -d ubuntu -r xenial -a amd64
```

Is there a way to indicate the create method that should run in unpriviledge mode ? 

Info on setting unprivileged-containers:
- https://www.stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/

**Comment by evgeni** [comment]
Hi,

which version of Ansible are you using? I can create unprivileged containers just fine with 2.1.1.0

My playbooks look like this:

```
  lxc_container:
    name: "{{ item.name }}"
    config: ".config/lxc/default.conf"
    template: "download"
    template_options: "-d debian -r jessie -a amd64"
```

See https://docs.ansible.com/ansible/lxc_container_module.html for docs :)
